### ISSUE TITLE
Enable plugin with edit comment dialog

### ISSUE THREAD

**Issue by jamesinc** [R-J/showAllEmojis#1]
Hey, I saw on the vanilla addons forum you weren't sure how to do this. I've done it for some of my own plugins, so I thought I'd just dump the relevant JS here for you. Basically you just need to hook an event that Vanilla's own JS broadcasts when the edit comment dialog is opened.

You can see it in use here:
https://github.com/jamesinc/imgur-upload/blob/master/js/imgurupload.js#L383

```
// ... snip
$( document ).on( "EditCommentFormLoaded", function ( evt, ctx ) {
	ctx.find( ".EditCommentForm" ).find( /* whatever el you're looking for */ ).each( function ( ) {

	});
// ... snip
```

**Comment by R-J** [comment]
That's great, thanks for your support! I guess it will take some time until I will be able to implement it, but I'll surely try to make it work and give feedback

**Comment by R-J** [comment]
Thousand thanks again, I fixed it and it seems to work like a charm now
