### ISSUE TITLE
Can't select emoji on Firefox

### ISSUE THREAD

**Issue by egorsmkv** [R-J/showAllEmojis#2]
After selecting emoji from the list input box is becoming empty.

**Comment by R-J** [comment]
Not sure I can help you. I have used Firefox when writing that plugin...

Sounds like a JavaScript problem. Do you see anything in the developer console?

**Comment by egorsmkv** [comment]
Yes, you are right. It is the JS problem.

```
ReferenceError: angry is not defined
```

Did you test your plugin with 2.3.1 version?

**Comment by R-J** [comment]
What a peaceful error message!

**Comment by R-J** [comment]
Not sure that it is the fault of this plugin. If I have to guess, It would say that there are some emoji definitions in the emoji set you are using which misbehave.

Yes, I've written that plugin for Vanilla 2.3.1 Which emoji set are you using? Have you tried another one?

**Comment by egorsmkv** [comment]
@R-J I found a bug. Check out my pull request.

**Comment by R-J** [comment]
Please try again with the version 0.3.0. I have changed quite a lot under the hood. The problem has been the missing ":" as you already found out - thanks again!
By looking at the plugin after some time I found that there is an easier and more efficient way to pass data from the PHP plugin to the script. Furthermore I use the assetPath and the format given by the manifest of a emoji set, which is far better than what I had before.

**Comment by egorsmkv** [comment]
I checked the version 0.3.0 and the plugin works fine. Thanks, Robin 👍

**Comment by R-J** [comment]
Nice to hear that, thanks for your feedback!
